### ISSUE TITLE
Compatibility with llncs

### ISSUE THREAD

**Issue by proteusGIT** [PierreSenellart/apxproof#30] opened 2019-06-06 10:06 UTC
I am using `\ProvidesClass{llncs}[2018/03/10 v2.20` and there is a different theorem style used when using apxproof.
I tried to use

        \makeatletter
        \AtBeginDocument{%
        \def\thmhead#1#2#3{%
        \thmname{#1}\thmnumber{\@ifnotempty{#1}{ }\@upn{#2}}%
        \thmnote{ {\normalfont (#3)}}}%
        }
        \makeatother

but that did not help.
Here is the example (where brackets are removed by apxproof):

      \documentclass{llncs}

        \usepackage{apxproof}

        \begin{document}

        \begin{definition}[Some test title]
        Some other nonsense.
        \end{definition}

        \end{document}

**Comment by proteusGIT** [comment] 2019-06-06 10:07
see also:
https://tex.stackexchange.com/questions/483029/apxproof-and-formatting-titles/484001#484001

**Comment by PierreSenellart** [comment] 2019-06-06 19:36
This document class has an annoyingly different behavior from regular document classes, as all theorem notes are surrounded with parentheses. This caused an issue in the formatting of repeated theorems, so I had initially “fixed” this issue by making this document class behave as standard ones. But I agree this is not a good solution, as apxproof should not impact the formatting in such a way.

The problem is not related to the redefinition of `\thmhead`, by the way, the document class makes no use of this macro.

Issue fixed in 12fc447 by adding code specific to this document class. Can you try and use the development version of apxproof.sty, at https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty and confirm this fixes the issue? If so, I will release v1.1.2 including this fix.

**Comment by PierreSenellart** [comment] 2019-06-06 19:46
Hum, looking into it a bit more, I realize I am mistaken: it's quite standard for document classes to use a format where there are parentheses around theorem notes. This means I will need to apply a similar solution to the more general case (the fix proposed on StackExchange is not satisfactory as it will mess up the formatting of repeated theorem entries). I will look into this.

For now, for the special case of llncs.cls, you can use the development version of apxproof.sty.

**Comment by PierreSenellart** [comment] 2019-10-07 20:21
The general issue of theorem notes (beyond the case of Springer document classes which was fixed in 12fc447) has been fixed in 68d154b. A new release will be done shortly, in the mean time the fixed code is available in the develop branch.

**Closed by PierreSenellart** 2019-10-07 20:21 UTC
